### ISSUE TITLE
[Bug] 7.0.7 Could not find a route for the "index" page of your site!

### ISSUE THREAD

**Issue by ayan4m1** [nozzle/react-static#1122]
### Reporting a bug?

This is the first I have worked with `react-static`. I ran `npm install -g react-static` and `react-static create`, created a directory using the basic template, changed into the new directory, and tried all of the following:

- `npx react-static start`
- `react-static start`
- `npx react-static build`

I get the same error each time.

```
  Error: Could not find a route for the "index" page of your site! This is required. Please create a page or specify a route and template for this page.

  - getRoutes.js:38 _callee$
    [v11.11.0]/[react-static]/src/static/getRoutes.js:38:13

  - runtime.js:45 tryCatch
    [v11.11.0]/[react-static]/[regenerator-runtime]/runtime.js:45:40

  - runtime.js:271 Generator.invoke [as _invoke]
    [v11.11.0]/[react-static]/[regenerator-runtime]/runtime.js:271:22

  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [v11.11.0]/[react-static]/[regenerator-runtime]/runtime.js:97:21

  - asyncToGenerator.js:3 asyncGeneratorStep
    [v11.11.0]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24

  - asyncToGenerator.js:25 _next
    [v11.11.0]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9

  - next_tick.js:81 processTicksAndRejections
    internal/process/next_tick.js:81:5
```

This appears to be a duplicate of #1094, but in that bug it was asked to open a new issue if there were new issues and that is what I am facing. The environment, repro steps, and solution of removing `path.resolve` in `static.config.js` all match my case.

Thank you for your time.

### Environment

```
  System:                                                     
    OS: Windows 10                                            
    CPU: (4) x64 Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz     
    Memory: 2.85 GB / 15.93 GB                                
  Binaries:                                                   
    Node: 11.11.0 - C:\Program Files\nodejs\node.EXE          
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD              
  Browsers:                                                   
    Edge: 44.17763.1.0                                        
    Internet Explorer: 11.0.17763.1                           
  npmPackages:                                                
    react: ^16.8.2 => 16.8.6                                  
    react-dom: ^16.8.2 => 16.8.6                              
    react-static: ^7.0.0 => 7.0.7                             
    react-static-plugin-reach-router: ^7.0.0 => 7.0.7         
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0              
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.0    
```

### Steps to Reproduce the problem

1.  `npm i -g react-static`
2.  `react-static create`
3.  select basic template
4.  cd into new project directory
5. `react-static start`

### Expected Behavior

No error, a working build out of the box.

**Comment by tannerlinsley** [comment]
This should be fixed as soon as we release #1128. Stay tuned!

**Comment by marqpdx** [comment]
I just updated to 7.0.8 and i'm still getting this error.

Same stack trace:
```
  Error: Could not find a route for the "index" page of your site! This is required. Please create a page or specify a route and template for this page.

  - getRoutes.js:38 _callee$
    [breathing-room]/[react-static]/src/static/getRoutes.js:38:13

  - runtime.js:45 tryCatch
    [breathing-room]/[regenerator-runtime]/runtime.js:45:40

  - runtime.js:271 Generator.invoke [as _invoke]
    [breathing-room]/[regenerator-runtime]/runtime.js:271:22

  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [breathing-room]/[regenerator-runtime]/runtime.js:97:21

  - asyncToGenerator.js:3 asyncGeneratorStep
    [breathing-room]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24

  - asyncToGenerator.js:25 _next
    [breathing-room]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

**Comment by tannerlinsley** [comment]
@marqpdx could you please give us a link to your repo/project?

**Comment by marqpdx** [comment]
@tannerlinsley here's a copy. i made you a collaborator. 
https://github.com/marqpdx/temp_br

**Comment by tannerlinsley** [comment]
@marqpdx It appears that you actually don't have an index page defined in your config. More than likely, you migrated from a previous version of react (v6 probably) where the `pages` directory was automatically compiled. 

You will need to use the new `react-static-plugin-source-filesystem` plugin to do this in v7. I would suggest starting with a fresh v7 project from `react-static create` and migrating your files over. That will provide you a lot more stability.

**Comment by marqpdx** [comment]
@tannerlinsley thanks for looking into it. i'll definitely start a fresh v7 project!
much appreciated, and thanks for jumping in so quickly.
React-static is awesome by the way!

**Comment by tannerlinsley** [comment]
Thanks!

**Comment by marqpdx** [comment]
so i went ahead and made a new v7 version, am porting everything over. i have my src/pages directory, and added the new plugin, as such:
```
      'react-static-plugin-source-filesystem',
      {
        location: path.resolve('./src/pages'),
      },
```
and i get this error (on the exact line from the `location` above in the plugin:
```

**Comment by tannerlinsley** [comment]
you must `import path from 'path'` in your config?

**Comment by marqpdx** [comment]
ok, that's good. i'll add a note to the doc for that.

`React-Static data hot-loader websocket encountered the following error:
  Error: Request failed with status code 404`

and  `ReferenceError: regeneratorRuntime is not defined`

**Comment by tannerlinsley** [comment]
Do you have a `.babelrc` file in the root of your project?

**Comment by marqpdx** [comment]
Yes, its contents are:
```
{
  "presets": ["react-static/babel-preset.js"]
}

```

This is from the default `react-static create`

**Comment by tannerlinsley** [comment]
Please open a new issue for this and we'll go from there. Make sure you paste a link to your updated repo :)

**Comment by marqpdx** [comment]
Will do, thanks!
