### ISSUE TITLE
getProps not defined for <Component>

### ISSUE THREAD

**Issue by pkrawc** [nozzle/react-static#15]
Hi there,

I threw together another markdown renderer this afternoon that I'm going to try and polish up and submit as an example. I'm running into an error I just don't understand the root of though.

I get `getProps not defined for: /components/avatar` and `No route defined for: /components/avatar` after spinning up a server with `yarn start` (npm start produces the same behavior.

### [Link to the repo.](https://github.com/pkrawc/react-static-markdown)

I'm just stumped and its probably cause I was staring at this for too long.

**Comment by tannerlinsley** [comment]
These are warnings (that I may remove, not sure yet). They are just meant to let you know that you (1) you don't have a static route defined for the avatar endpoint, so no static html will be exported and (2) there is also no `getProps` function defined for that same route (which is obvious because of #1).

It should still build.  

What do you think about those warnings?

I am planning on removing the `getProps` warning for sure.

**Comment by derekperkins** [comment]
I think it's still valuable. Maybe there needs to be a log level setting to increase/decrease the amount of those types of warnings.

**Comment by pkrawc** [comment]
I'm fine with the warnings, although I'm confused why they appear, since I am indeed defining both routes and getProps in the static.config.js.

**Comment by tannerlinsley** [comment]
It says it's looking for a route with the path `/components/avatar`. If I'm understanding correctly, that would mean there would need to be an `avatar.md` file in your documentation folder no?

**Comment by tannerlinsley** [comment]
Okay, I'm seeing now. The `postTwo.md` has a `path` in the front-matter. I'll need to dig in more...

**Comment by pkrawc** [comment]
I forgot a switch that I just updated. Errors are still there, but at least the files render now.

**Comment by tannerlinsley** [comment]
There is actually a bug with those warnings.  I'll have a fix out in a bit.

**Comment by mplis** [comment]
@tannerlinsley I'm seeing a bug where my page's component doesn't render unless I define a `getProps` for that page in `static.config.js`, even if it's just a dummy object. Is that related to this?

**Comment by tannerlinsley** [comment]
This issue should be resolved.

**Comment by tannerlinsley** [comment]
@mplis That shouldn't be necessary at all. Please upgrade to the latest and double check :)

**Comment by pkrawc** [comment]
Still getting the same error, just slightly more verbose. Would you take a look at that repo and point out anything you see as incorrect?

**Comment by tannerlinsley** [comment]
Sure thing
