### ISSUE TITLE
Error in render function crashes browser tab.

### ISSUE THREAD

**Issue by Nikica-Luger** [nozzle/react-static#150]
I do not know whether this is a React issue or another library but i tried it on the naked `basic` example of `react-static` repo. I also assume that it might be me doing something wrong... 

In `Home.js` i added:
```js
import Component from '../Component'
...
  <div>
    <Component/>
  </div>
```

while `Component` is simply:

```js
import React from 'react'


class Component extends React.Component {
  render () {
    throw 'error'; // WE HAVE AN ERROR IN THE RENDER FUNCTION!
    return (
      <div>
        TEST
      </div>
    );
  }
}

export default Component;
```

Now something ***ugly*** happens 😵 : 

![pasted image 0](https://user-images.githubusercontent.com/32647249/32692990-ee4b31ee-c722-11e7-98b1-e00825efd4b7.png)

Unfortunately i cannot provide any error log, as the console freezes completely.

**Comment by EmilTholin** [comment]
Hi @Nikica-Luger!

This seems to be related to using [React with the Webpack dev server](https://github.com/facebook/react/issues/10441). It might be worth investigating if default settings could be changed [to this](https://github.com/facebook/react/issues/10441#issuecomment-341465258), but I'm not sure if that's desirable.

**Comment by Nikica-Luger** [comment]
In a component without `getSiteProps`, the error was ***not*** thrown.

**Comment by EmilTholin** [comment]
Hi @Nikica-Luger! 

Great find! It seems like it goes into an infinite loop because of the `componentWillMount` in `getSiteProps`. An error occurs, the `sitePropsPromise` is resolved, and setState is called. This seems to happen definitely. If you temporarily comment out the [`setState`](https://github.com/nozzle/react-static/blob/master/src/index.js#L255-L257), it doesn't go into an infinite loop.

**Comment by Nikica-Luger** [comment]
Hey @EmilTholin,

thanks for the fast feedback! I commented out the referrenced piece directly in the library code, so it corresponds to:
```js
                case 3:
                    ...
                case 7:
                  this.setState({
                    siteProps: siteProps
                  });
```
in the generated code.

Unfortunately the error is still causing an infinite loop. Also i saw that `getRouteProps` has a similar flow.

Anyway, i assume commenting out the library code won't be our final solution. If this is a general problem any render errors are currently not debuggable, which is quite severe for any project. I do not have enough understanding of the library code and the problem to dare a PR on my own.

**Comment by EmilTholin** [comment]
I commented it out in the source and re-compiled, and it got rid of the infinite loop. I definitely agree that commenting out that code isn't a solution to the problem. I was just sharing my findings for whoever wants to pick up the ball!

**Comment by Nikica-Luger** [comment]
Great @EmilTholin, so we know at least where it is! Probably it was the recompilation step. Yes, maybe @tannerlinsley should take a look at it, as it's really at the heart of the library.
