### ISSUE TITLE
Can't use fs module in the static.config.js file

### ISSUE THREAD

**Issue by mattwelson** [nozzle/react-static#6]
I wanted to create markdown files inside a folder, but when I tried to use the fs module (or fs-extra) the build process fails.
Minimum steps:
Add `import fs from 'fs'` to the `static.config.js` file
`$ yarn start`
<img width="345" alt="screen shot 2017-10-07 at 3 56 49 pm" src="https://user-images.githubusercontent.com/3399530/31304150-3dcdcc16-ab78-11e7-9917-51084079e5e8.png">

**Comment by tannerlinsley** [comment]
I'll get on this asap

**Comment by pkrawc** [comment]
I was working on this this afternoon as well. `vfile` also fails the build.

**Comment by robbieferrero** [comment]
Similar issue: [Can't resolve 'fs' when bundle with webpack #447](https://github.com/webpack-contrib/css-loader/issues/447)
It seems to be a bug in webpack. I attempted a local fix for something I was working on and it got past the build/serve issue, but I ran into a different error with certain 'fs' methods using the workaround outlined in that thread – Adding to `webpack.config.dev.js`:
```
node: {
  fs: 'empty'
}
```

**Comment by tannerlinsley** [comment]
I've almost resolved this. Fix should be out hopefully by late tonight

**Comment by tannerlinsley** [comment]
This should be fixed in the latest release (4b2a6db50ff48e6f21f71033a7a6ced623fa6839, react-static@1.0.41). Can either of you confirm?

**Comment by robbieferrero** [comment]
👍 It's looking good for me, with a caveat...
If I `react-static create` then place my 'fs' based changes in static.config.js, run `yarn start` - I still get the same error.
If I `npm install` inside the project directory and run `yarn start` again, it works fine.

**Comment by tannerlinsley** [comment]
ah crap. forgot to update the deps to be more lenient in the examples. hold that thought...

**Comment by tannerlinsley** [comment]
Should be good now. Confirm again?

**Comment by robbieferrero** [comment]
Lookin' good!

**Comment by tannerlinsley** [comment]
Awesome! Thanks guys :)
