### ISSUE TITLE
Hot Reloading not working on Routes.

### ISSUE THREAD

**Issue by rdhox** [nozzle/react-static#616]
### Are you reporting a bug?
Yes

### Is this a feature request?
No

### Environment

1.  `react-static -v`: 5.9.3
2.  `node -v`: v10.0.0
3.  `yarn --version or npm -v`: 6.0.1
4.  Operating system: Ubuntu 16.04
5.  Browser and version (if relevant):

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  react-static create
2.  choose the "style-components" templates
3.  npm start
4.  go to localhost:3000, and click on "about" link
5. go to src/containers/About.js and modify the text, and save
6. the page on the browser is not hot reloaded with the change

### Expected Behavior
Reload of the page with the change in the About.js file.

**Comment by intermundos** [comment]
Get same behavior. 

macOS High Sierra
Node 9.11
npm 6.0.1

**Comment by WiNloSt** [comment]
I try with many versions, seems like v. `5.8.6` is the latest version that hot reload still works. And when I upgraded to v. `5.8.8` and upwards the hot reload ain't work again.

**Comment by tannerlinsley** [comment]
Upgrade to latest version, should now be working :)

**Comment by rdhox** [comment]
Thank Tanner.
I'm very sorry but still not working for me, same configuration, react-static update to the version 5.9.5.

**Comment by nthtran** [comment]
Can confirm `5.8.6` is the latest version that still works.

**Comment by cooperka** [comment]
5.8.6 works, 5.8.7 broken, latest 5.9.5 broken. Can confirm this commit breaks it: https://github.com/nozzle/react-static/commit/7a684cd660abbc29d89c453fb1889db244227c69.

@tannerlinsley do you mind re-opening, please?

**Comment by arobert93** [comment]
5.9.7 does not work.

**Comment by blesswinsamuel** [comment]
Adding `{modules:false}` worked for me

Complete .babelrc:
```
{
  "presets": [["env", {"modules": false}], "stage-0", "react"],
  "plugins": [
    [
      "universal-import",
      {
        "disableWarnings": true
      }
    ],
    "transform-class-properties",
    [
      "transform-runtime",
      {
        "helpers": false,
        "polyfill": false,
        "regenerator": true,
        "moduleName": "babel-runtime"
      }
    ]
  ],
  "env": {
    "development": {
      "plugins": ["react-hot-loader/babel"]
    },
    "test": {
      "presets": [["env", {"modules": false}], "stage-0", "react"],
    }
  },
  "compact": false
}
```

**Comment by andrewmartin** [comment]
I found a quick, hacky workaround is to add 

```js
export default hot(module)(Component);
```

To EACH component you want to hot reload. Really not ideal.
