### ISSUE TITLE
[v6] [sass example] TypeError: this[NS] is not a function

### ISSUE THREAD

**Issue by lexaurin** [nozzle/react-static#753]
### Are you reporting a bug?

Error when building sass example on v6 branch

### Environment

1.  `react-static -v`: `v6`
2.  `node -v`: `v8.11.4`

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  `react-static create --template sass --name foo`
2.  `cd foo`
3.  `yarn build`

```
yarn build
yarn run v1.9.4
$ react-static build

=> Info: No 'siteRoot' is defined in 'static.config.js'. This is suggested for absolute url's and a sitemap.xml to be automatically generated.

=> Cleaning dist...
=> [✓] Dist cleaned (0s)
=> Building Routes...
=> [✓] Routes Built (0.1s)
=> Building Templates
=> [✓] Templates Built (0s)
=> Copying public directory...
=> [✓] Public directory copied (0s)
=> Bundling App...
Version: webpack 4.18.0
Time: 3306ms
Built at: 2018-09-17 10:11:00
                                        Asset       Size  Chunks  Chunk Names
           templates/vendors~main.02ebbf5e.js    212 KiB       6  vendors~main
                     static/logo.9ff8fc2e.png   27.8 KiB          
          templates/src-pages-404.cbe7cab6.js  306 bytes       1  src-pages-404
        templates/src-pages-about.bfd9f5c4.js  399 bytes       2  src-pages-about
         templates/src-pages-blog.2b61a73a.js  529 bytes       3  src-pages-blog
    templates/src-containers-Post.d9751b0a.js  436 bytes       4  src-containers-Post
        templates/src-pages-index.b0891039.js  492 bytes       5  src-pages-index
                             main.e5da9f3b.js   83.9 KiB       0  main
                         main.e5da9f3b.js.map   87.8 KiB       0  main
      templates/src-pages-404.cbe7cab6.js.map  616 bytes       1  src-pages-404
    templates/src-pages-about.bfd9f5c4.js.map  738 bytes       2  src-pages-about
     templates/src-pages-blog.2b61a73a.js.map   1.22 KiB       3  src-pages-blog
templates/src-containers-Post.d9751b0a.js.map   1.01 KiB       4  src-containers-Post
    templates/src-pages-index.b0891039.js.map   1.34 KiB       5  src-pages-index
       templates/vendors~main.02ebbf5e.js.map    684 KiB       6  vendors~main
  [1] /Users/lex/workspace/test-rs-build-sass/node_modules/react/index.js 190 bytes {6} [built]
  [2] /Users/lex/workspace/test-rs-build-sass/node_modules/react-hot-loader/index.js 228 bytes {6} [built]
 [12] ../lib/index.js 5.42 KiB {0} [built]
 [13] ../lib/client/methods.js 23.6 KiB {0} [built]
 [14] (webpack)/buildin/global.js 489 bytes {6} [built]
 [33] /Users/lex/workspace/test-rs-build-sass/node_modules/react-dom/index.js 1.33 KiB {6} [built]
 [47] /Users/lex/workspace/test-rs-build-sass/dist/react-static-routes.js 9.29 KiB {0} [built]
 [53] /Users/lex/workspace/test-rs-build-sass/node_modules/react/cjs/react.production.min.js 5.98 KiB {6} [built]
 [54] /Users/lex/workspace/test-rs-build-sass/node_modules/react-dom/cjs/react-dom.production.min.js 92.2 KiB {6} [built]
 [55] /Users/lex/workspace/test-rs-build-sass/node_modules/schedule/index.js 196 bytes {6} [built]
 [57] /Users/lex/workspace/test-rs-build-sass/node_modules/react-hot-loader/dist/react-hot-loader.production.min.js 1.32 KiB {6} [built]
[101] ../lib/client/components/Redirect.js 7.77 KiB {0} [built]
[102] ../lib/client/components/Link.js 6.51 KiB {0} [built]
[106] /Users/lex/workspace/test-rs-build-sass/src/app.scss 1.99 KiB {0} [built] [failed] [1 error]
[107] /Users/lex/workspace/test-rs-build-sass/src/index.js + 1 modules 1.33 KiB {0} [built]
      | /Users/lex/workspace/test-rs-build-sass/src/index.js 748 bytes [built]
      | /Users/lex/workspace/test-rs-build-sass/src/App.js 586 bytes [built]
    + 94 hidden modules

ERROR in /Users/lex/workspace/test-rs-build-sass/src/app.scss
Module build failed (from /Users/lex/workspace/test-rs-build-sass/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
TypeError: this[NS] is not a function
    at childCompiler.runAsChild (/Users/lex/workspace/test-rs-build-sass/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:147:15)
    at compile (/Users/lex/workspace/react-static/node_modules/webpack/lib/Compiler.js:296:11)
    at hooks.afterCompile.callAsync.err (/Users/lex/workspace/react-static/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lex/workspace/react-static/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/lex/workspace/react-static/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/Users/lex/workspace/react-static/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lex/workspace/react-static/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/lex/workspace/react-static/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/Users/lex/workspace/react-static/node_modules/webpack/lib/Compilation.js:1294:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lex/workspace/react-static/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/lex/workspace/react-static/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/lex/workspace/react-static/node_modules/webpack/lib/Compilation.js:1285:32)
    at _fn1.then._result1 (eval at create (/Users/lex/workspace/react-static/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ /Users/lex/workspace/test-rs-build-sass/src/App.js 5:0-20
 @ /Users/lex/workspace/test-rs-build-sass/src/index.js
Child extract-css-chunks-webpack-plugin css-loader/index.js??ref--4-oneOf-0-1!../../test-rs-build-sass/node_modules/sass-loader/lib/loader.js??ref--4-oneOf-0-2!../../test-rs-build-sass/src/app.scss:
    [0] ./css-loader??ref--4-oneOf-0-1!/Users/lex/workspace/test-rs-build-sass/node_modules/sass-loader/lib/loader.js??ref--4-oneOf-0-2!/Users/lex/workspace/test-rs-build-sass/src/app.scss 663 bytes {0} [built]
    [1] ./css-loader/lib/css-base.js 2.21 KiB {0} [built]

                => There were ERRORS during the prod build stage! :(
                => Fix them and try again!
              
=> [✓] App Bundled (4s)
=> Fetching Site Data...
=> [✓] Site Data Downloaded (0s)
=> Fetching Route Data...
=> [=========================================================================================================] 105/105 100% 17500/s 0.0s 
=> [✓] Route Data Downloaded (0s)
=> Exporting Route Data...
=> [=========================================================================================================] 105/105 100% 35000/s 0.0s 
=> [✓] Route Data Exported (0s)
=> Exporting Shared Route Data...
=> [=] 1/1 100% Infinity/s 0.0s 
=> [✓] Shared Route Data Exported (0s)
=> Exporting HTML across 8 threads...
=> [=========================================================================================================] 105/105 100% 621/s 0.0s 
=> [✓] HTML Exported (4.6s)
✨  Done in 11.38s.
```

### Expected Behavior

No build error

**Comment by tannerlinsley** [comment]
The latest beta release fixes this issue. This was a problem that I discovered and fixed with webpack's and universal's css loaders not handling loader context properly. See #736

**Comment by shivanandwp** [comment]
I have the same issue:

```ERROR in /Users/SomeUser/Desktop/WP-Dev/_Projects/JS/wp-demo/src/app.scss
Module build failed (from /Users/SomeUser/Desktop/WP-Dev/_Projects/JS/wp-demo/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
TypeError: this[NS] is not a function
    at childCompiler.runAsChild (/Users/SomeUser/Desktop/WP-Dev/_Projects/JS/wp-demo/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:147:15)
    at compile (/usr/local/lib/node_modules/react-static/node_modules/webpack/lib/Compiler.js:290:11)
    at hooks.afterCompile.callAsync.err (/usr/local/lib/node_modules/react-static/node_modules/webpack/lib/Compiler.js:547:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/react-static/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/react-static/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/usr/local/lib/node_modules/react-static/node_modules/webpack/lib/Compiler.js:544:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/react-static/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/react-static/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/usr/local/lib/node_modules/react-static/node_modules/webpack/lib/Compilation.js:1296:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/react-static/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/react-static/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/usr/local/lib/node_modules/react-static/node_modules/webpack/lib/Compilation.js:1287:32)
    at _promise1.then._result1 (eval at create (/usr/local/lib/node_modules/react-static/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:18:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 @ /Users/SomeUser/Desktop/WP-Dev/_Projects/JS/wp-demo/src/App.js 2:40-59
 @ /Users/SomeUser/Desktop/WP-Dev/_Projects/JS/wp-demo/src/index.js
Child extract-css-chunks-webpack-plugin css-loader/index.js??ref--4-oneOf-0-1!../../../../../../Users/SomeUser/Desktop/WP-Dev/_Projects/JS/wp-demo/node_modules/sass-loader/lib/loader.js??ref--4-oneOf-0-2!../../../../../../Users/SomeUser/Desktop/WP-Dev/_Projects/JS/wp-demo/src/app.scss:
    [0] ./css-loader??ref--4-oneOf-0-1!/Users/SomeUser/Desktop/WP-Dev/_Projects/JS/wp-demo/node_modules/sass-loader/lib/loader.js??ref--4-oneOf-0-2!/Users/SomeUser/Desktop/WP-Dev/_Projects/JS/wp-demo/src/app.scss 944 bytes {0} [built]
    [1] ./css-loader/lib/css-base.js 1.9 KiB {0} [built]```

**Comment by lexaurin** [comment]
Issue was not fixed, still failing on `TypeError: this[NS] is not a function`.  

Tried clean install and build of 6.0.0-beta.22

```
yarn build
yarn run v1.9.4
$ react-static build

=> Info: No 'siteRoot' is defined in 'static.config.js'. This is suggested for absolute url's and a sitemap.xml to be automatically generated.

=> Cleaning dist...
=> [✓] Dist cleaned (0s)
=> Building Routes...
=> [✓] Routes Built (0.1s)
=> Building Templates
=> [✓] Templates Built (0s)
=> Copying public directory...
=> [✓] Public directory copied (0s)
=> Bundling App...
Version: webpack 4.20.2
Time: 10336ms
Built at: 2018-09-30 22:34:09
                                        Asset        Size  Chunks  Chunk Names
           templates/vendors~main.1c60224d.js     294 KiB       6  vendors~main
                     static/logo.9ff8fc2e.png    27.8 KiB          
          templates/src-pages-404.44d13256.js   306 bytes       1  src-pages-404
        templates/src-pages-about.2ab51d1c.js   399 bytes       2  src-pages-about
         templates/src-pages-blog.763e35a3.js   529 bytes       3  src-pages-blog
    templates/src-containers-Post.8364fe9d.js   436 bytes       4  src-containers-Post
        templates/src-pages-index.cab64932.js   492 bytes       5  src-pages-index
                             main.0a3f7fa7.js     9.5 KiB       0  main
                         main.0a3f7fa7.js.map    21.2 KiB       0  main
      templates/src-pages-404.44d13256.js.map   609 bytes       1  src-pages-404
    templates/src-pages-about.2ab51d1c.js.map   731 bytes       2  src-pages-about
     templates/src-pages-blog.763e35a3.js.map     1.2 KiB       3  src-pages-blog
templates/src-containers-Post.8364fe9d.js.map  1010 bytes       4  src-containers-Post
    templates/src-pages-index.cab64932.js.map    1.31 KiB       5  src-pages-index
       templates/vendors~main.1c60224d.js.map     765 KiB       6  vendors~main
  [0] /Users/lex/workspace/test-rs-foo/node_modules/react/index.js 169 bytes {6} [built]
  [2] /Users/lex/workspace/test-rs-foo/node_modules/react-hot-loader/index.js 613 bytes {6} [built]
 [10] ../lib/utils/shared.js 8.05 KiB {6} [built]
 [12] ../lib/index.js 4.62 KiB {6} [built]
 [13] ../lib/browser/index.js 16.6 KiB {6} [built]
 [14] (webpack)/buildin/global.js 797 bytes {6} [built]
 [33] /Users/lex/workspace/test-rs-foo/node_modules/react-dom/index.js 1.19 KiB {6} [built]
 [48] /Users/lex/workspace/test-rs-foo/dist/react-static-routes.js 7.56 KiB {0} [built]
 [54] /Users/lex/workspace/test-rs-foo/node_modules/react/cjs/react.production.min.js 6.48 KiB {6} [built]
 [55] /Users/lex/workspace/test-rs-foo/node_modules/react-dom/cjs/react-dom.production.min.js 93.6 KiB {6} [built]
 [58] /Users/lex/workspace/test-rs-foo/node_modules/react-hot-loader/dist/react-hot-loader.production.min.js 1.73 KiB {6} [built]
 [89] ../lib/browser/components/RouteData.js 10.8 KiB {6} [built]
[103] ../lib/browser/components/Link.js 5.27 KiB {6} [built]
[107] /Users/lex/workspace/test-rs-foo/src/app.scss 1.93 KiB {0} [built] [failed] [1 error]
[108] /Users/lex/workspace/test-rs-foo/src/index.js + 1 modules 1.17 KiB {0} [built]
      | /Users/lex/workspace/test-rs-foo/src/index.js 663 bytes [built]
      | /Users/lex/workspace/test-rs-foo/src/App.js 502 bytes [built]
    + 95 hidden modules

ERROR in /Users/lex/workspace/test-rs-foo/src/app.scss
Module build failed (from /Users/lex/workspace/test-rs-foo/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
TypeError: this[NS] is not a function
    at childCompiler.runAsChild (/Users/lex/workspace/test-rs-foo/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:147:15)
    at compile (/Users/lex/workspace/test-rs-foo/node_modules/webpack/lib/Compiler.js:290:11)
    at hooks.afterCompile.callAsync.err (/Users/lex/workspace/test-rs-foo/node_modules/webpack/lib/Compiler.js:547:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lex/workspace/test-rs-foo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lex/workspace/test-rs-foo/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/lex/workspace/test-rs-foo/node_modules/webpack/lib/Compiler.js:544:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lex/workspace/test-rs-foo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lex/workspace/test-rs-foo/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/lex/workspace/test-rs-foo/node_modules/webpack/lib/Compilation.js:1296:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lex/workspace/test-rs-foo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lex/workspace/test-rs-foo/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/lex/workspace/test-rs-foo/node_modules/webpack/lib/Compilation.js:1287:32)
    at _promise1.then._result1 (eval at create (/Users/lex/workspace/test-rs-foo/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:18:1)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ /Users/lex/workspace/test-rs-foo/src/App.js 2:40-59
 @ /Users/lex/workspace/test-rs-foo/src/index.js
Child extract-css-chunks-webpack-plugin ../../css-loader/index.js??ref--4-oneOf-0-1!../../sass-loader/lib/loader.js??ref--4-oneOf-0-2!../../../src/app.scss:
    [0] /Users/lex/workspace/test-rs-foo/node_modules/css-loader??ref--4-oneOf-0-1!/Users/lex/workspace/test-rs-foo/node_modules/sass-loader/lib/loader.js??ref--4-oneOf-0-2!/Users/lex/workspace/test-rs-foo/src/app.scss 647 bytes {0} [built]
    [1] /Users/lex/workspace/test-rs-foo/node_modules/css-loader/lib/css-base.js 1.9 KiB {0} [built]

                => There were ERRORS during the prod build stage! :(
                => Fix them and try again!
              
=> [✓] App Bundled (11.5s)
=> Fetching Site Data...
=> [✓] Site Data Downloaded (0s)
=> Fetching Route Data...
=> [=========================================================================================================] 105/105 100% 15000/s 0.0s 
=> [✓] Route Data Downloaded (0s)
=> Exporting Route Data...
=> [=========================================================================================================] 105/105 100% 21000/s 0.0s 
=> [✓] Route Data Exported (0s)
=> Exporting Shared Route Data...
=> [=] 1/1 100% Infinity/s 0.0s 
=> [✓] Shared Route Data Exported (0s)
=> Exporting HTML across 8 threads...
=> [=========================================================================================================] 105/105 100% 1479/s 0.0s 
=> [✓] HTML Exported (2.7s)
✨  Done in 17.80s.
```

**Comment by lexaurin** [comment]
I see now, it's because `react-static-plugin-sass` was not updated on npm yet. Could you please release 1.0.2 version @tannerlinsley ?

**Comment by lexaurin** [comment]
So I tried to build master version of `react-static-plugin-sass` and linking it to my react-static example with sass. Still failing but error is now different:

```
yarn build
yarn run v1.9.4
$ react-static build
  Error: Cannot find module 'webpack'
  
  - module.js:538 Function.Module._resolveFilename
    module.js:538:15
  
  - module.js:468 Function.Module._load
    module.js:468:25
  
  - module.js:587 Module.require
    module.js:587:17
  
  - module.js:11 require
    internal/module.js:11:18
  
  - index.js:11 Object.<anonymous>
    [react-static-plugin-sass]/[extract-css-chunks-webpack-plugin]/dist/index.js:11:16
  
  - module.js:643 Module._compile
    module.js:643:30
  
  - index.js:83 Module._compile
    [test-rs-foo2]/[pirates]/lib/index.js:83:24
  
  - module.js:654 Module._extensions..js
    module.js:654:10
  
  - index.js:88 Object.newLoader [as .js]
    [test-rs-foo2]/[pirates]/lib/index.js:88:7
  
  - module.js:556 Module.load
    module.js:556:32
  


=> Info: No 'siteRoot' is defined in 'static.config.js'. This is suggested for absolute url's and a sitemap.xml to be automatically generated.

=> Cleaning dist...
  TypeError: Cannot read property 'DIST' of undefined
  
  - bundle.js:48 DIST
    [test-rs-foo2]/[react-static]/src/commands/bundle.js:48:32
  
  - runtime.js:62 tryCatch
    [test-rs-foo2]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [test-rs-foo2]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [test-rs-foo2]/[regenerator-runtime]/runtime.js:114:21
  
  - bundle.js:24 asyncGeneratorStep
    [test-rs-foo2]/[react-static]/lib/commands/bundle.js:24:103
  
  - bundle.js:26 _next
    [test-rs-foo2]/[react-static]/lib/commands/bundle.js:26:194
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
  
  - module.js:686 Function.Module.runMain
    module.js:686:11
  
  - bootstrap_node.js:187 startup
    bootstrap_node.js:187:16
  

error Command failed with exit code 1.
```
