### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by max80713** [nozzle/react-static#883]
### Environment

1.  `react-static -V`: 6.0.4
2.  `node -v`: v8.9.0
3.  `npm -v`: 5.5.1
4.  Operating system: macOS Mojave 10.14
5.  Browser and version (if relevant):

### Steps to Reproduce the problem

1.  react-static create
2.  yarn build
3.  yarn serve

#### result

navigate to http://localhost:3000/blog and show in browser:

```
Oh-no! Something’s gone wrong!

Reload Component
TypeError: Cannot read property 'map' of undefined

    in a
    in F
    in q
    in DefaultRouter
    in RouterScroller
    in s
    in ErrorBoundary
    in Router
    in Unknown
    in Unknown
```

### Expected Behavior

A normal post page just like the one after `yarn start`

### Reproducible Demo

I have no demo, but it is just the react-static app using the basic template.

**Comment by paavohuhtala** [comment]
I can confirm. Attempting to navigate to the blog in a production build just crashes the page.

Here's a repo you can repro with: https://github.com/OpenSAGE/opensage.github.io/tree/gh-pages

**Comment by tannerlinsley** [comment]
Hmm... I thought I fixed this bug, but apparently not. This is most likely a race condition when updating the location of the page and the RouteData component in the previous or next template attempting to pull stale or unloaded data.

I'll look into this more. Thanks for the repro.

**Comment by tannerlinsley** [comment]
We fixed some issues with routing race conditions in the last update. Please update to the latest version and try the build again. Reopen if problem still exists.

**Comment by arnediekmann** [comment]
I can still reproduce the issue consistently after updating to 6.0.11.
