### ISSUE TITLE
Material UI example not working

### ISSUE THREAD

**Issue by cbroberg** [nozzle/react-static#896]
### Environment

1.  `react-static -V`: 6.0.6
2.  `node -v`: v11.1.0
3.  `npm -v`: 6.4.1
4.  Operating system: MacOS 10.11.6 (15G22010)
5.  Browser and version (if relevant): Version 71.0.3578.98 (Official Build) (64-bit)

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Freshly installed react-static material-ui template
2.  Updated MUI packages to @material-ui ... everywhere + all other packages
3.  yarn start
4. Errors, tried to delete node_modules and yarn.lock and run yarn again
5. Same errors
6. Material-ui/colors is not an npm (in case you should suggest i didn't install the right packages)

### Reproducible Demo
Package.json

{
  "name": "react-static-example-material-ui",
  "version": "6.0.0-beta.28",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "react-static start",
    "build": "react-static build",
    "serve": "serve dist -p 3000"
  },
  "dependencies": {
    "@material-ui/core": "^3.7.0",
    "@material-ui/icons": "^3.0.1",
    "axios": "^0.18.0",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-hot-loader": "^4.6.2",
    "react-jss": "^8.6.1",
    "react-static": "^6.0.6"
  },
  "devDependencies": {
    "eslint-config-react-tools": "1.x.x",
    "serve": "^10.1.1"
  },
  "gitHead": "350700130b7501622eac16aa139107c684b62b01"
}

ERRORS:

yarn run v1.10.1
$ react-static start
  Error: Cannot find module '@material-ui/colors'
  
  - loader.js:587 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:587:15
  
  - loader.js:513 Function.Module._load
    internal/modules/cjs/loader.js:513:25
  
  - loader.js:643 Module.require
    internal/modules/cjs/loader.js:643:17
  
  - helpers.js:22 require
    internal/modules/cjs/helpers.js:22:18
  
  - theme.js:1 Object.<anonymous>
    /Users/christianbroberg/Apps/codebuild/my-static-site/src/theme.js:1:1
  
  - loader.js:707 Module._compile
    internal/modules/cjs/loader.js:707:30
  
  - index.js:83 Module._compile
    [my-static-site]/[pirates]/lib/index.js:83:24
  
  - loader.js:718 Module._extensions..js
    internal/modules/cjs/loader.js:718:10
  
  - index.js:88 Object.newLoader [as .js]
    [my-static-site]/[pirates]/lib/index.js:88:7
  
  - loader.js:605 Module.load
    internal/modules/cjs/loader.js:605:32
  
  - loader.js:544 tryModuleLoad
    internal/modules/cjs/loader.js:544:12
  
  - loader.js:536 Function.Module._load
    internal/modules/cjs/loader.js:536:3
  
  - loader.js:643 Module.require
    internal/modules/cjs/loader.js:643:17
  
  - helpers.js:22 require
    internal/modules/cjs/helpers.js:22:18
  
  - static.config.js:8 Object.<anonymous>
    /Users/christianbroberg/Apps/codebuild/my-static-site/static.config.js:8:1
  
  - loader.js:707 Module._compile
    internal/modules/cjs/loader.js:707:30
  
  - index.js:83 Module._compile
    [my-static-site]/[pirates]/lib/index.js:83:24
  
  - loader.js:718 Module._extensions..js
    internal/modules/cjs/loader.js:718:10
  
  - index.js:88 Object.newLoader [as .js]
    [my-static-site]/[pirates]/lib/index.js:88:7
  
  - loader.js:605 Module.load
    internal/modules/cjs/loader.js:605:32
  
  - loader.js:544 tryModuleLoad
    internal/modules/cjs/loader.js:544:12
  
  - loader.js:536 Function.Module._load
    internal/modules/cjs/loader.js:536:3
  
  - loader.js:643 Module.require
    internal/modules/cjs/loader.js:643:17
  
  - helpers.js:22 require
    internal/modules/cjs/helpers.js:22:18
  
  - getConfig.js:235 require
    [my-static-site]/[react-static]/src/static/getConfig.js:235:20
  
  - runtime.js:62 tryCatch
    [my-static-site]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [my-static-site]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [my-static-site]/[regenerator-runtime]/runtime.js:114:21
  
  - getConfig.js:46 asyncGeneratorStep
    [my-static-site]/[react-static]/lib/static/getConfig.js:46:103
  
  - getConfig.js:48 _next
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:194
  
  - getConfig.js:48 
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:364
  
  - new Promise
  
  - getConfig.js:48 
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:97
  
  - getConfig.js:231 buildConfigFromPath
    [my-static-site]/[react-static]/src/static/getConfig.js:231:26
  
  - getConfig.js:248 buildConfigFromPath
    [my-static-site]/[react-static]/src/static/getConfig.js:248:24
  
  - runtime.js:62 tryCatch
    [my-static-site]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [my-static-site]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [my-static-site]/[regenerator-runtime]/runtime.js:114:21
  
  - getConfig.js:46 asyncGeneratorStep
    [my-static-site]/[react-static]/lib/static/getConfig.js:46:103
  
  - getConfig.js:48 _next
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:194
  
  - getConfig.js:48 
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:364
  
  - new Promise
  
  - getConfig.js:48 
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:97
  
  - getConfig.js:417 getConfig
    [my-static-site]/[react-static]/lib/static/getConfig.js:417:23
  
  - start.js:28 Object._callee3$
    [my-static-site]/[react-static]/src/commands/start.js:28:9
  
  - runtime.js:62 tryCatch
    [my-static-site]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [my-static-site]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [my-static-site]/[regenerator-runtime]/runtime.js:114:21
  
  - start.js:24 asyncGeneratorStep
    [my-static-site]/[react-static]/lib/commands/start.js:24:103
  
  - start.js:26 _next
    [my-static-site]/[react-static]/lib/commands/start.js:26:194
  
  - start.js:26 
    [my-static-site]/[react-static]/lib/commands/start.js:26:364
  

  Error: Cannot find module '@material-ui/colors'
  
  - loader.js:587 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:587:15
  
  - loader.js:513 Function.Module._load
    internal/modules/cjs/loader.js:513:25
  
  - loader.js:643 Module.require
    internal/modules/cjs/loader.js:643:17
  
  - helpers.js:22 require
    internal/modules/cjs/helpers.js:22:18
  
  - theme.js:1 Object.<anonymous>
    /Users/christianbroberg/Apps/codebuild/my-static-site/src/theme.js:1:1
  
  - loader.js:707 Module._compile
    internal/modules/cjs/loader.js:707:30
  
  - index.js:83 Module._compile
    [my-static-site]/[pirates]/lib/index.js:83:24
  
  - loader.js:718 Module._extensions..js
    internal/modules/cjs/loader.js:718:10
  
  - index.js:88 Object.newLoader [as .js]
    [my-static-site]/[pirates]/lib/index.js:88:7
  
  - loader.js:605 Module.load
    internal/modules/cjs/loader.js:605:32
  
  - loader.js:544 tryModuleLoad
    internal/modules/cjs/loader.js:544:12
  
  - loader.js:536 Function.Module._load
    internal/modules/cjs/loader.js:536:3
  
  - loader.js:643 Module.require
    internal/modules/cjs/loader.js:643:17
  
  - helpers.js:22 require
    internal/modules/cjs/helpers.js:22:18
  
  - static.config.js:8 Object.<anonymous>
    /Users/christianbroberg/Apps/codebuild/my-static-site/static.config.js:8:1
  
  - loader.js:707 Module._compile
    internal/modules/cjs/loader.js:707:30
  
  - index.js:83 Module._compile
    [my-static-site]/[pirates]/lib/index.js:83:24
  
  - loader.js:718 Module._extensions..js
    internal/modules/cjs/loader.js:718:10
  
  - index.js:88 Object.newLoader [as .js]
    [my-static-site]/[pirates]/lib/index.js:88:7
  
  - loader.js:605 Module.load
    internal/modules/cjs/loader.js:605:32
  
  - loader.js:544 tryModuleLoad
    internal/modules/cjs/loader.js:544:12
  
  - loader.js:536 Function.Module._load
    internal/modules/cjs/loader.js:536:3
  
  - loader.js:643 Module.require
    internal/modules/cjs/loader.js:643:17
  
  - helpers.js:22 require
    internal/modules/cjs/helpers.js:22:18
  
  - getConfig.js:235 require
    [my-static-site]/[react-static]/src/static/getConfig.js:235:20
  
  - runtime.js:62 tryCatch
    [my-static-site]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [my-static-site]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [my-static-site]/[regenerator-runtime]/runtime.js:114:21
  
  - getConfig.js:46 asyncGeneratorStep
    [my-static-site]/[react-static]/lib/static/getConfig.js:46:103
  
  - getConfig.js:48 _next
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:194
  
  - getConfig.js:48 
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:364
  
  - new Promise
  
  - getConfig.js:48 
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:97
  
  - getConfig.js:231 buildConfigFromPath
    [my-static-site]/[react-static]/src/static/getConfig.js:231:26
  
  - getConfig.js:254 FSWatcher.buildConfigFromPath
    [my-static-site]/[react-static]/src/static/getConfig.js:254:28
  
  - runtime.js:62 tryCatch
    [my-static-site]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [my-static-site]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [my-static-site]/[regenerator-runtime]/runtime.js:114:21
  
  - getConfig.js:46 asyncGeneratorStep
    [my-static-site]/[react-static]/lib/static/getConfig.js:46:103
  
  - getConfig.js:48 _next
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:194
  
  - getConfig.js:48 
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:364
  
  - new Promise
  
  - getConfig.js:48 FSWatcher.<anonymous>
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:97
  
  - events.js:182 FSWatcher.emit
    events.js:182:13
  
  - index.js:200 FSWatcher.<anonymous>
    [my-static-site]/[chokidar]/index.js:200:38
  
  - index.js:241 FSWatcher._emit
    [my-static-site]/[chokidar]/index.js:241:5
  
  - fsevents-handler.js:329 FSWatcher.<anonymous>
    [my-static-site]/[chokidar]/lib/fsevents-handler.js:329:12
  
  - fsevents-handler.js:378 FSWatcher.<anonymous>
    [my-static-site]/[chokidar]/lib/fsevents-handler.js:378:7
  
  - fs.js:162 FSReqCallback.oncomplete
    fs.js:162:5
  

  TypeError: Cannot read property 'DIST' of undefined
  
  - start.js:37 DIST
    [my-static-site]/[react-static]/src/commands/start.js:37:36
  
  - runtime.js:62 tryCatch
    [my-static-site]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [my-static-site]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [my-static-site]/[regenerator-runtime]/runtime.js:114:21
  
  - start.js:24 asyncGeneratorStep
    [my-static-site]/[react-static]/lib/commands/start.js:24:103
  
  - start.js:26 _next
    [my-static-site]/[react-static]/lib/commands/start.js:26:194
  
  - start.js:26 
    [my-static-site]/[react-static]/lib/commands/start.js:26:364
  
  - new Promise
  
  - start.js:26 
    [my-static-site]/[react-static]/lib/commands/start.js:26:97
  
  - start.js:28 
    [my-static-site]/[react-static]/src/commands/start.js:28:9
  
  - getConfig.js:253 FSWatcher._callee4$
    [my-static-site]/[react-static]/src/static/getConfig.js:253:44
  
  - runtime.js:62 tryCatch
    [my-static-site]/[regenerator-runtime]/runtime.js:62:40
  
  - runtime.js:288 Generator.invoke [as _invoke]
    [my-static-site]/[regenerator-runtime]/runtime.js:288:22
  
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [my-static-site]/[regenerator-runtime]/runtime.js:114:21
  
  - getConfig.js:46 asyncGeneratorStep
    [my-static-site]/[react-static]/lib/static/getConfig.js:46:103
  
  - getConfig.js:48 _next
    [my-static-site]/[react-static]/lib/static/getConfig.js:48:194
  
  - next_tick.js:77 process.internalTickCallback
    internal/process/next_tick.js:77:7

**Comment by tannerlinsley** [comment]
Not sure if you saw, but this is happening: https://github.com/nozzle/react-static/issues/895.

In a nutshell, examples will be no more and guides will be the way forward. Clearly the materialUI example is out of date, too. 

Would you be interested in writing the guide for using Material UI? Here are some examples: https://github.com/nozzle/react-static/tree/master/docs/guides

**Comment by cbroberg** [comment]
I am so close to giving up. I almost got everything working with the styled-components example but the yarn build static site didn't serve the correct route neither with yarn serve or a push to a surge.sh site had the same errors. Every time i tried the blog route it failed and after a manual reload of the page it worked. But that is not acceptable.

**Comment by tannerlinsley** [comment]
You're right. We're still working out some kinks around all of the integrations and v6. If you have a link to your repo we could take a look at and try to reproduce these issues, it will help us fix the issues much faster. Thanks for your support!

**Comment by cbroberg** [comment]
@tannerlinsley I am not skilled enough to write a guide for using react-static. I wish. But working on it though. I can test and research different aspects of OS solutions but if they do not work as prescribed I'm not fortunate to solve all issues on my own. I have senior devs but try to check out and sanitize potential software solutions and I must admit that react-static looked very promising.  The site we are building needs Material-ui and the example could have served as the door to select react-static. If the styled-components example had worked when pushed to a server I might have continued with that boilerplate, but now I'm a bit lost. I will push both examples to a repo and let you know. Thanks for your interest and help.

**Comment by tannerlinsley** [comment]
You bet. Both of those examples were working great for everyone in v5 just a days ago, so I'm sure it's something small we just need to iron out. Let me know when you get those repos up to test with 😄

**Comment by cbroberg** [comment]
Hi @tannerlinsley. I have pushed 2 repos here:

https://github.com/cbroberg/react-static-sc
https://github.com/cbroberg/react-static-mui 

The -sc works on localhost but has some routing error while served. I have included an image of the error on a web page and in the repo. 

The -mui crashes big time on localhost and couldn't get any further with that, which is actually the one I want working the most. But both should work :) 

Hope you or someone can help, let me know if anyone needs to be added as a collaborator on the repo to push back changes if you find a fix for it.

Thanks in advance. 

P.S. Are you the father of chartjs, we use that intensely? :)

**Comment by tannerlinsley** [comment]
I'll try and  take a look in the next day or two. I wouldn’t say I’m the
father of chart.js... more like the step parent.

 I haven’t been involved in that project for over a year now but originally
me and Evert timberg created v2 which is what most people know and love
today.

**Comment by tannerlinsley** [comment]
KRSHHHH. Requesting write permissions. Over.

**Comment by tannerlinsley** [comment]
So you'll notice I pushed some changes to your MUI repo.

Most of the changes should speak for themselves, but you'll see notes anywhere I needed to leave them. Let me know if that gets you where you'd like to be.

**Comment by cbroberg** [comment]
Thanks @tannerlinsley. I got the localhost version of react-static-mui working, but it has the same routing error as the https://github.com/cbroberg/react-static-sc has when trying to yarn serve or surge.sh the static site. 

![screen shot 2018-12-19 at 01 20 42](https://user-images.githubusercontent.com/486755/50192056-01ccf180-0331-11e9-96c7-96f869e0da55.png)

**Comment by cbroberg** [comment]
I have now tried AWS where we under Apache host all our stuff and it still doesn't work with the routing under /blog. 

I have now tried 3 different cases and all with the exact same result:
http://kanata.webhouse.net/
http://react-static-mui.surge.sh/
http://localhost:3002/ (with yarn server as proposed in react-static package.json)

If you try the 2 real domains above and go to http://kanata.webhouse.net/blog you'll see what i mean. 

Can you please try the above and possibly clone the repo https://github.com/cbroberg/react-static-mui again and do a yarn build + yarn serve on it as well. 

I am pretty sure it has to do with the router because the Network tab in Chrome Dev Tools doesn't show activity before i manually reload the page and then the content arrives. But as soon as i click the menu again or one of the blog posts the problem is instant again. 

react-dom.production.min.js:3835 TypeError: Cannot read property 'map' of undefined
    at blog.js:15
    at yi (react-dom.production.min.js:3525)
    at Ki (react-dom.production.min.js:4648)
    at Xi (react-dom.production.min.js:4669)
    at Na (react-dom.production.min.js:5057)
    at Ma (react-dom.production.min.js:5024)
    at Ea (react-dom.production.min.js:4959)
    at ta (react-dom.production.min.js:4885)
    at Object.enqueueForceUpdate (react-dom.production.min.js:2892)
    at Routes.x.forceUpdate (react.production.min.js:78)

It's like it doesn't get the { posts } parameter before you manually reload. 

Thanks in advance.

**Comment by Pixelatex** [comment]
@cbroberg it's not your routing that's failing.(well directly atleast) The error that occurs is caused by your props that are missing. Your server cannot load the data jsons for their respective routes, only when it's a new refresh.

**Comment by cbroberg** [comment]
So do you have any examples you know for sure that works with yarn serve on the DIST build static version? @Pixelatex @tannerlinsley 

Please advice.

**Comment by tannerlinsley** [comment]
This usually has to do with hosting but not always. The basic template is
very stable and should work both in dev mode and after being built and
served with a static file server.

**Comment by cbroberg** [comment]
Still doesn't work.

Could you try the following with your package:

$ react-static create
$ Select Basic
$ yarn 
$ yarn build
$ yarn serve

And then tell me that you do not get and error when you access /blog ...

**Comment by tannerlinsley** [comment]
I just released a very major patch for some issues with routeInfo.json files and also the dev server. Both should be more consistent in behavior now and I hope will fix the problems you're experiencing.

Can you upgrade and confirm?

**Comment by tannerlinsley** [comment]
FYI, this guide is a work in progress, but should help a bit!

- [Guides - Material UI](https://github.com/nozzle/react-static/blob/master/docs/guides/material-ui.md)

**Comment by cbroberg** [comment]
Thanks @tannerlinsley and @Pixelatex that's what you would call an early Christmas present because now it actually works. So I was right and not just a douche complaining over my own lack of engineering skills ;)

Now I can commence my real react-static trials 👍 

Merry Christmas to ya'll and a happy new year 💯
