### ISSUE TITLE
Have to restart `yarn start` after every few minutes

### ISSUE THREAD

**Issue by sgup** [nozzle/react-static#905]
### Are you reporting a bug?

Dev server stops reloading changes. Network request to `localhost:3000` is not responsive, and yarn `=> [✓] Build Updated` stops happening.

### Environment

1.  `react-static -V`: 6.0.6
2.  `node -v`: v11.0.0
3.  `npm -v`: 6.4.1
4.  Operating system: OS X v 10.14
5.  Browser and version (if relevant): Chrome Version 71.0.3578.98

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Built off `styled-components` template
2.  Applied changes from https://github.com/nozzle/react-static/pull/889
3.  Run server, code changes after 5 mins stop updating and server becomes unresponsive.

### Expected Behavior

Server reloads with changes

**Comment by ScriptedAlchemy** [comment]
Ive seen this before, maybe. Can you check your processes and let me know if theres multiple node process running, either consuming lots of cpu or just loads of dead ones. 

If you clear them out (terminate all node processes) and watch them, do you see a bunch of idel or constantly active node process show up over development time. 

If so, i think this is something buggy in yarn, because this is happening to me on other projects based off my Universal Icarus platform.

**Comment by tannerlinsley** [comment]
My guess is this has to do with the faulty hot reloading setup we're also
trying to fix.

**Comment by ScriptedAlchemy** [comment]
Question, does this happen if you use NPM, npx and not yarn to start tasks? I notice this problem specifically with yarn and on many different platforms

**Comment by sgup** [comment]
@ScriptedAlchemy same issue with `npm start`. I think it's an issue with `react-static start`

**Comment by ScriptedAlchemy** [comment]
okay yeah, then this must be an issue there. you are not like adding new files or anything? which would cause those new files to not be seen by the build? Trying to cover the common cases i have seen before. 

just normal changes to existing files, then after a little dev ... it just stops working?

**Comment by sgup** [comment]
@ScriptedAlchemy Yes exactly, normal changes inside js files. I know I have to restart the server if I add/remove files or edit the config.

**Comment by ScriptedAlchemy** [comment]
Hmm. This is strange, I’ll have to touch base with tanner and see what it could be. 

This seems very strange and may be related to our CMR? Or an old version of HMR

**Comment by ScriptedAlchemy** [comment]
@tannerlinsley could this be related to either old HMR or RS cold module reloading? Perhaps the cache is overflowing or something?

**Comment by tannerlinsley** [comment]
Could be. I still think it's something with the hmr or data data hot reloading. It's difficult to profile too. I'll look into it more today.

**Comment by tannerlinsley** [comment]
I just released a big fix for routeInfo and dev server data. We should investigate this again with the latest version as things could hopefully be resolved.

**Comment by mjsisley** [comment]
I was experiencing issues with this (had to restart server to see changes) when starting from the `basic` template. Bumping the version of `react-hot-loader` to latest resolved the issue for me.

**Comment by ScriptedAlchemy** [comment]
Yeah I have been talking with the maintainer of RHL, we need to recheck the implementation and make sure we have implemented it in the new way. It’s far more stable as well

**Comment by tannerlinsley** [comment]
Is this still happening for people?

**Comment by ScriptedAlchemy** [comment]
Yeah Anton did some major work on RHL, which has made it far more stable.

**Comment by cy** [comment]
@mjsisley which version of react-hot-loader did you upgrade to? I upgraded to 4.6.5, latest release but am still getting this issue.

**Comment by cy** [comment]
answering my own question here, 4.6.3 works. 4.6.4 ❌4.6.4 ❌

**Comment by tannerlinsley** [comment]
As ar as I can tell, this has been fixed and alleviated with the latest releases to RHL. Reopen if needed!

**Comment by ScriptedAlchemy** [comment]
Thrilled to see this resolved and know what the problem was.

**Comment by sgup** [comment]
Still happening with:

```
"dependencies": {
    "@reach/router": "^1.2.1",
    "axios": "^0.18.0",
    "history": "^4.7.2",
    "lodash": "^4.17.11",
    "marked": "^0.6.0",
    "papaparse": "^4.6.2",
    "react": "^16.8.2",
    "react-dom": "^16.8.0",
    "react-flexa": "^0.9.0",
    "react-ga": "^2.5.6",
    "react-hot-loader": "^4.8.0",
    "react-static": "^6.0.6",
    "react-static-plugin-google-analytics": "^0.0.0",
    "react-static-plugin-styled-components": "^6.0.5",
    "styled-components": "^4.1.1",
    "styled-react-modal": "^1.2.1"
  },
  "devDependencies": {
    "babel-plugin-styled-components": "^1.3.0",
    "eslint-config-react-tools": "1.x.x",
    "react-static-plugin-favicons": "^1.0.0",
    "serve": "^10.1.1"
  },
```

Also using dynamic routing with https://github.com/nozzle/react-static/blob/master/docs/guides/dynamic-routes-reach-router.md
